apiVersion: v1
kind: Service
metadata:
  name: car-web-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:637423621367:certificate/21d7eab8-834a-427a-9a9a-7cc400df4999
    # Only run TLS on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: car-web
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: car-web-deploy
  labels:
    app: car-web
spec:
  selector:
    matchLabels:
      app: car-web
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: car-web
        tier: frontend
    spec:
      containers:
      - name: car-web
        image: juanedo/car-web-V7:01
        ports:
        - containerPort: 80
